### PR TITLE
convertToHTML emoji fixes

### LINKED ISSUE #85: Incorrect offsets in entities after emojis
If there is an emoji (with `.length >= 2`) before an entity. The entity originalText argument in the `entityToHTML` is incorrect. Here's a breaking test:

```js
  it('handles offset of entities after an emoji', () => {
    const contentState = buildContentState([
      {
        text: '👍 Santi Albo',
        type: 'unstyled',
        depth: 0,
        entityRanges: [{
          offset: 0,
          length: 1,
          key: 0,
        }, {
          offset: 2,
          length: 10,
          key: 1,
        }],
      }
    ], {
      0: {
        type: 'emoji',
        mutability: 'IMMUTABLE',
        data: {
          emojiUnicode: '👍'
        }
      },
      1: {
        type: 'mention',
        mutability: 'SEGMENTED',
        data: {
          href: '/users/1'
        }
      }
    });

    const result = convertToHTML({
      entityToHTML(entity, originalText) {
        if (entity.type === 'emoji') {
          return entity.data.emojiUnicode;
        } else if (entity.type === 'mention') {
          return <a href={entity.data.href}>{originalText}</a> // <-- originalText here is "anti Albo"
        }
      }
    })(contentState);
    // result === '<p>👍 S<a href="/users/1">anti Albo</a></p>'
    expect(result).toBe('<p>👍 <a href="/users/1">Santi Albo</a></p>');
  });

```

### PR DESCRIPTION
**Pull request by benbriggs**
fixes #85

uses `Array.from` via the array spread to split strings on codepoints rather than splitting an emoji of > 1 character into multiple string characters

### CODE REVIEW

File: test/spec/convertToHTML.js [hunk 1]
```diff
@@ -844,4 +844,50 @@ describe('convertToHTML', () => {
...
+        }
+      }
+    });
+
+    const result = convertToHTML({
+      entityToHTML(entity, originalText) {
+        if (entity.type === 'emoji') {
+          return entity.data.emojiUnicode;
+        } else if (entity.type === 'mention') {
+          return <a href={entity.data.href}>{originalText}</a> // <-- originalText here is "anti Albo"
```
Comment (chriswong929) [inline test/spec/convertToHTML.js]: missing semicolon

File: test/spec/convertToHTML.js [hunk 2]
```diff
@@ -844,4 +844,50 @@ describe('convertToHTML', () => {
...
+        }
+      }
+    })(contentState);
+    // result === '<p>👍 S<a href="/users/1">anti Albo</a></p>'
```
Comment (chriswong929) [inline test/spec/convertToHTML.js]: Don't need this

File: test/spec/convertToHTML.js (hunk 1 above)
Comment (benbriggs) [inline test/spec/convertToHTML.js]: ah yup, the linter didn't like this either
